name: qhcare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.20.1
  get: ^4.6.5
  dio: ^5.1.2
  icons_plus: ^5.0.0
  flutter_svg: ^2.0.2
  connectivity_plus: ^6.0.3
  get_storage: ^2.1.1
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.1.11
  share_plus: ^11.0.0
  flutter_native_splash: ^2.2.19
  
  google_sign_in: ^6.1.3
  sign_in_with_apple: ^6.1.1
  flutter_facebook_auth: ^7.1.1
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  firebase_auth: ^5.1.2
  firebase_dynamic_links: ^6.0.3
  flutter_inappwebview: ^6.1.5
  photo_view: ^0.15.0
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
          
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/fulllogo.png
  android_12:
      image: assets/images/slogo.png
      icon_background_color: "#000000"
      image_dark: assets/images/slogo.png
      icon_background_color_dark: "#000000"